server:
  session-timeout: 1800
  port: 48082
spring:
  application:
    name: GatewayZuulService
  cloud:
    polaris:
      address: grpc://127.0.0.1:8081
    tencent:
      metadata:
        content:
          a: 1
        transitive:
          - a
zuul:
  routes:
    GatewayCalleeService:
      serviceId: GatewayCalleeService
      path: /GatewayCalleeService/**
