name: Codecov

on:
  push:
    branches:
      - 2023.0
      - 2022.0
      - 2021.0
      - 2020.0
      - hoxton
      - greenwich
  pull_request:
    branches:
      - 2023.0
      - 2022.0
      - 2021.0
      - 2020.0
      - hoxton
      - greenwich

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Test with Maven
        run: mvn clean test -B -U -Psonatype
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
