name: License checker

on:
  push:
    branches:
      - 2023.0
      - 2022.0
      - 2021.0
      - 2020.0
      - hoxton
      - greenwich
  pull_request:
    branches:
      - 2023.0
      - 2022.0
      - 2021.0
      - 2020.0
      - hoxton
      - greenwich
jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Check License Header
        uses: apache/skywalking-eyes@v0.4.0
